// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZAYpAavLEaYLFK53R3-3HrjEMo7RnfH8',
    appId: '1:169318759576:web:cb716f1ad4b507a4c5e4ed',
    messagingSenderId: '169318759576',
    projectId: 'spelec-carljulfranz',
    authDomain: 'spelec-carljulfranz.firebaseapp.com',
    storageBucket: 'spelec-carljulfranz.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGMq68wBcRFAq6gaTKhwNxqyZswjENS9g',
    appId: '1:169318759576:android:b2a6b3bf647d48a8c5e4ed',
    messagingSenderId: '169318759576',
    projectId: 'spelec-carljulfranz',
    storageBucket: 'spelec-carljulfranz.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdM2Qegfgwa_hqZQFTf4hVM3B3lhP0SCk',
    appId: '1:169318759576:ios:a4fa478c7137cd82c5e4ed',
    messagingSenderId: '169318759576',
    projectId: 'spelec-carljulfranz',
    storageBucket: 'spelec-carljulfranz.appspot.com',
    iosClientId: '169318759576-19ajfsknbr7iagfvb5mioneogtjm9hvm.apps.googleusercontent.com',
    iosBundleId: 'com.example.spelecMidterms1',
  );
}
